name: CI/CD Frontend Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.13.1
    - name: Install dependencies
      run: npm install
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to DigitalOcean Droplet
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SERVER_USER : ${{secrets.SERVER_USER}}
        run: |
          sshpass -p "${PRIVATE_KEY}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} << 'EOF'
          cd /var/www/html
          git pull origin main
          cd /var/www/html/frontend
          npm install
          npm run build
          cp -r /var/www/html/frontend/dist/* /var/www/html
          cd /var/www/html
          systemctl restart nginx
          EOF
